# Generated by Django 3.2.7 on 2021-09-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offering',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
