# Generated by Django 3.2.1 on 2021-05-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='demo', max_length=200)),
                ('video', models.FileField(upload_to='video')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
