# Generated by Django 3.2.7 on 2021-09-15 15:57

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('slug', models.TextField(unique=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('description', djrichtextfield.models.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('slug', models.TextField(unique=True)),
                ('image', models.ImageField(upload_to='media')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media')),
                ('facebook_ulr', models.URLField(blank=True)),
                ('linkedin_ulr', models.URLField(blank=True)),
                ('twitter_ulr', models.URLField(blank=True)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
