# Generated by Django 3.2.7 on 2021-09-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='image_light',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
