# Generated by Django 3.2.7 on 2021-09-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_offering_image_light'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebook_ulr',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='linkedin_ulr',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='twitter_ulr',
            new_name='twitter_url',
        ),
    ]
