# Generated by Django 3.2.7 on 2021-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210916_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='url',
            field=models.URLField(default='https://www.linkedin.com'),
        ),
    ]
