# Generated by Django 3.2.7 on 2021-09-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_prduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prduct',
            new_name='Product',
        ),
    ]
